"""initial tables

Revision ID: 4ba66b3e04fa
Revises: 
Create Date: 2026-06-27 04:57:31.714482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ba66b3e04fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'premium', name='userplan'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('vehicle_plate', sa.String(), nullable=True),
    sa.Column('context', sa.Enum('rental', 'purchase', 'personal', 'insurance', name='scancontext'), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'processing', 'complete', 'failed', name='scanstatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('scan_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('panel', sa.Enum('front', 'back', 'left', 'right', 'hood', 'roof', name='panel'), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('annotated_url', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('is_rejected', sa.Boolean(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('defect_type', sa.Enum('dent', 'scratch', 'crack', 'other', name='defecttype'), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'moderate', 'severe', name='severity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mask_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_w', sa.Float(), nullable=True),
    sa.Column('bbox_h', sa.Float(), nullable=True),
    sa.Column('mask_area_px', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['scan_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('scan_images')
    op.drop_table('reports')
    op.drop_table('scan_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
